CREATE SCHEMA `ssm` DEFAULT CHARACTER SET utf8mb4 ;

CREATE TABLE `ssm`.`sys_user`(
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(50) NOT NULL,
  `account` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
);
